version: "3"
services:
  node-server:
    image: node:14-alpine
    command: sh -c 'npm install && npm run start'
    ports:
      - "3000:3000"
    container_name: node-server
    working_dir: /root/server
    volumes:
      - ./server:/root/server:cached
  react-client:
    image: node:14-alpine
    command: sh -c 'npm install && npm run start'
    ports:
      - "8081:8081"
    container_name: react-client
    depends_on:
      - node-server
    working_dir: /root/client
    volumes:
      - ./client:/root/client:cached
